### ISSUE TITLE
Hardware Setup

### ISSUE THREAD

**Issue by nmalley** [Tom-Archer/gmusicaiy#2]
Hi
Would you be able to share your hardware set up using the AIY kit and scroll phat?

looking to create something similar and wondered what the best was was?
thanks

**Comment by Tom-Archer** [comment]
Hi @nmalley - I soldered headers on to the 5 I2C pins in the top left of the Voice HAT. I then connected jumper cables from the 5V, GND, SCL and SDA pins on the Voice HAT to the appropriate pins on the Scroll pHAT. See [here](https://pinout.xyz/pinout/scroll_phat) for the pin layout. Hope that helps.

**Comment by nmalley** [comment]
Thanks for that, looking forward to trying it out, it's a nice touch to the voice kit.
